name: CI
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle

      - name: Build
        run: ./gradlew -s build -x test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle

      - name: Lint
        run: |
          ./gradlew detekt

  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle
