spring:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: groovyarea

  data:
    mongodb:
      uri: mongodb://root:1234@localhost/product?authSource=admin

    redis:
      host: localhost
      port: 6379
