name: CI
on:
  push:
    branches-ignore:
      - main

jobs:
  product-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Current Working Directory
        run: |
            echo "Current Working Directory: $(pwd)"

      - name: move to Product
        run: cd /home/runner/work/groovy-chicken-breast-shop/groovy-chicken-breast-shop/product

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle

      - name: Build
        run: ./gradlew -s build -x test

  product-lint:
    runs-on: ubuntu-latest
    steps:
      - name: move to Product
        run: cd product

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle

      - name: Lint
        run: |
          ./gradlew detekt

  product-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: move to Product
        run: cd product

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle
